apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.52
          ports:
            - containerPort: 5775   # UDP - Thrift compact
            - containerPort: 6831   # UDP - Thrift compact
            - containerPort: 6832   # UDP - Thrift binary
            - containerPort: 5778   # HTTP - Config
            - containerPort: 16686  # HTTP - Query UI
            - containerPort: 14250  # gRPC - Model
            - containerPort: 14268  # HTTP - Thrift
            - containerPort: 14269  # HTTP - Admin
            - containerPort: 4317   # OTLP gRPC
            - containerPort: 4318   # OTLP HTTP
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: SPAN_STORAGE_TYPE
              value: "memory"
            - name: MEMORY_MAX_TRACES
              value: "50000"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: observability-dev
spec:
  type: ClusterIP
  ports:
    - name: jaeger-thrift
      port: 14268
      targetPort: 14268
    - name: grpc
      port: 14250
      targetPort: 14250
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: observability-dev
spec:
  type: ClusterIP
  ports:
    - name: query-http
      port: 16686
      targetPort: 16686
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: observability-dev
spec:
  type: ClusterIP
  ports:
    - name: thrift-compact
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: thrift-binary
      port: 6832
      targetPort: 6832
      protocol: UDP
    - name: config
      port: 5778
      targetPort: 5778
  selector:
    app: jaeger
